# fly.toml app configuration file generated for angiday-redis on 2025-10-08T05:37:00+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'angiday-redis'
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
