app = "angiday-ollama"

[build]
  image = "ollama/ollama:latest"

[processes]
  app = { size = "shared-cpu-2x" }   # increase CPU/RAM (try 2x or larger)

[[mounts]]
  source = "ollama_data"
  destination = "/root/.ollama"

[[services]]
  internal_port = 11434
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 8080

  [[services.http_checks]]
    path = "/"
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"